version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_DATABASE=digital_legacy_vault
      - DB_USERNAME=admin
      - DB_PASSWORD=secure_password
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=strong_root_password
      - MYSQL_DATABASE=digital_legacy_vault
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secure_password
    volumes:
      - vault_db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  vault_db_data:
