name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, exif, pcntl, bcmath, sockets, intl
          
      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist
          npm install
          npm run build
          
      - name: Run tests
        run: |
          php artisan key:generate
          php artisan test
          npm run test
          
      - name: Static analysis
        run: |
          phpstan analyze
          php-cs-fixer fix --dry-run
