name: Deployment Pipeline

on:
  push:
    tags:
      - 'v*.*.*'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup SSH
        uses: shimataro/ssh-action@v0.5.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/digital-legacy-vault
            git pull origin main
            composer install --no-dev
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan queue:restart
